---
# Autojump remembers where you cd to the most, and ranks those directories
# highest, so you can type 'j reports' and it takes you to /.../.../../reports

# Install packages
- include_tasks: packages.osx.yml
  when: "ansible_distribution == 'MacOSX'"

- name: Setup bashrc file
  template:
    src: bashrc.j2
    dest: ~/.bashrc
    mode: 0755
    backup: yes
