---
- hosts: all
  gather_facts: yes 
  vars_files:
    - vars.yml
  roles:
    - role: bash
      tags: bash
    - role: git
      tags: git
    - role: vim
      tags: vim
    - role: ruby
      tags: ruby
