---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  roles:
    - bash
    - git
    - role: vim
      pathogen_plugins:
        - repo: https://github.com/tpope/vim-sensible.git
        - repo: https://github.com/tpope/vim-fugitive.git
        - repo: https://github.com/joshdick/onedark.vim.git
    - ruby
