#!/usr/bin/env bash
# bootstrap installs things.

# Assume everyone's on OS X and run Homebrew (*nix-ers beware)
OS=`uname -s`
if [ "$OS" == "Darwin" ]; then
	. setup/homebrew
else
  echo "Please install the following packages for this distro:"
  echo "  autojump: https://github.com/joelthelion/autojump"
  echo "  rbenv: https://github.com/sstephenson/rbenv"
  echo "  ruby-build: https://github.com/sstephenson/ruby-build"
fi

# Run the install (I'd like to pull this out of rake, eventually)
rake install

